"""Synthetic replication of displacement inside a finite context window.

The specification is frozen in ``data/prereg/01-displacement-replication.md`` (generative model,
analytic predictions P1/P1b/P2/P3, grid, KATs 1-4 and the falsification criterion Q1/Q2/Q3). This
module implements the API of that pre-registration; the orchestration of the full grid lives in
``run_replication.py``.

Identifiers and dictionary keys are kept verbatim from the frozen implementation (Portuguese names
such as ``celulas``, ``semente``, ``avaliar_quebra``): they become the column names of
``output/replication/celulas.csv`` and the keys of ``output/replication/resumo.json``, which are
regenerated byte for byte. Arithmetic, the order of random draws and every constant are verbatim.
"""

from __future__ import annotations

import itertools
import math
import os
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor

import numpy as np
from scipy.stats import norm, rankdata

FONTES = ("A", "B", "C")
COMBOS = ("A", "B", "C", "AB", "BC", "AC", "ABC")
L_JANELA = 146
PI = 0.2

GRADE_T = (90, 180, 365)
GRADE_LAM_A = (0.1, 0.2)
GRADE_LAM_B = (0.3, 0.6)
GRADE_LAM_C = (1, 3, 6)
GRADE_D_A = (0.3, 0.5)
GRADE_D_B = (0.15, 0.25)
GRADE_D_C = (0, 0.025, 0.05, 0.1, 0.2)


# --- grid ---------------------------------------------------------------------------------------


def celulas() -> list[dict]:
    """Return the 720 cells of the grid.

    The order is ``itertools.product(T, lam_A, lam_B, lam_C, d_A, d_B, d_C)``.

    Returns
    -------
    list of dict
        One ``{"T": ..., "lam": {...}, "d": {...}}`` per cell.
    """
    saida = []
    for T, lam_a, lam_b, lam_c, d_a, d_b, d_c in itertools.product(
        GRADE_T, GRADE_LAM_A, GRADE_LAM_B, GRADE_LAM_C, GRADE_D_A, GRADE_D_B, GRADE_D_C
    ):
        saida.append(
            {
                "T": T,
                "lam": {"A": lam_a, "B": lam_b, "C": lam_c},
                "d": {"A": d_a, "B": d_b, "C": d_c},
            }
        )
    return saida


# --- analytic prediction ------------------------------------------------------------------------


def delta2_analitico(combo, lam, d, T, L=L_JANELA) -> float:
    """Return the expected-count separability Delta^2 of a combination of sources.

    The visible horizon is ``h = min(T, L / sum(lam))``; ``L=None`` means ``h = T`` and an empty
    rate sum gives ``Delta^2 = 0``.
    """
    Lam = sum(lam[s] for s in combo)
    if Lam == 0:
        return 0.0
    h = T if L is None else min(T, L / Lam)
    return sum(lam[s] * h * d[s] ** 2 for s in combo)


def auc_analitica(combo, lam, d, T, L=L_JANELA) -> float:
    """Return the predicted AUC, ``Phi(sqrt(Delta^2) / sqrt(2))``."""
    delta2 = delta2_analitico(combo, lam, d, T, L)
    return float(norm.cdf(math.sqrt(delta2) / math.sqrt(2)))


def saturada(combo, lam, T, L=L_JANELA) -> bool:
    """Return whether the window saturates in expectation, ``sum(lam) * T >= L``.

    ``L=None`` never saturates.
    """
    if L is None:
        return False
    return sum(lam[s] for s in combo) * T >= L


def padrao_p3(a: dict) -> bool:
    """Return whether the AUCs follow the sign pattern of Table 4 (pre-registration, P3)."""
    return (
        a["AB"] > a["A"]
        and a["BC"] > a["C"]
        and a["AC"] < a["A"]
        and a["BC"] < a["B"]
        and a["ABC"] < a["AB"]
        and a["C"] < min(a["A"], a["B"])
    )


def ordem_completa(a: dict) -> bool:
    """Return whether the decreasing AUC order equals the full order of Table 4."""
    ordenado = sorted(COMBOS, key=lambda c: a[c], reverse=True)
    return list(ordenado) == ["AB", "A", "ABC", "AC", "B", "BC", "C"]


def regiao_p3_analitica() -> tuple[int, int, int]:
    """Count the P3 region on the analytic AUCs of the grid.

    Returns
    -------
    tuple of int
        ``(n_cells, n_with_sign_pattern, n_with_full_order)``.
    """
    n_celulas = 0
    n_padrao = 0
    n_ordem = 0
    for cel in celulas():
        n_celulas += 1
        a = {c: auc_analitica(c, cel["lam"], cel["d"], cel["T"]) for c in COMBOS}
        if padrao_p3(a):
            n_padrao += 1
        if ordem_completa(a):
            n_ordem += 1
    return n_celulas, n_padrao, n_ordem


# --- empirical AUC and standard error -----------------------------------------------------------


def auc_mann_whitney(scores, y) -> float:
    """Return the Mann-Whitney AUC with mid-ranks for ties (0.5 when every score ties)."""
    scores = np.asarray(scores, dtype=float)
    pos = np.asarray(y).astype(bool)
    n1 = int(np.sum(pos))
    n0 = len(pos) - n1
    if n1 == 0 or n0 == 0:
        return 0.5
    postos = rankdata(scores, method="average")
    r_pos = float(np.sum(postos[pos]))
    return (r_pos - n1 * (n1 + 1) / 2) / (n1 * n0)


def se_hanley_mcneil(auc, n_pos, n_neg) -> float:
    """Return the standard error of an AUC (Hanley and McNeil, 1982)."""
    A = auc
    Q1 = A / (2 - A)
    Q2 = 2 * A**2 / (1 + A)
    numerador = A * (1 - A) + (n_pos - 1) * (Q1 - A**2) + (n_neg - 1) * (Q2 - A**2)
    return math.sqrt(numerador / (n_pos * n_neg))


# --- random draws -------------------------------------------------------------------------------


def rng_para(semente, i_celula, i_combo):
    """Return an independent stream per (seed, cell, combination), with no global state."""
    return np.random.default_rng([semente, i_celula, i_combo])


def escores_contagens_fixas(n: dict, d: dict, N, rng):
    """Draw oracle scores with FIXED counts (KAT 1).

    ``score ~ Normal((y - 0.5) Delta^2, sqrt(Delta^2))``.
    """
    y = rng.random(N) < PI
    delta2 = sum(n[s] * d[s] ** 2 for s in n)
    media = (y.astype(float) - 0.5) * delta2
    scores = rng.normal(media, math.sqrt(delta2))
    return scores, y


def simular_reducao(combo, lam, d, T, N, rng, L=L_JANELA):
    """Simulate by the exact reduction of the window composition.

    The window composition is ``Multinomial(min(N_tot, L), lam / sum(lam))`` with
    ``N_tot ~ Poisson(sum(lam) * T)``; given the counts, the oracle score is Normal.
    """
    y = rng.random(N) < PI
    Lam = sum(lam[s] for s in combo)
    if Lam == 0:
        return np.zeros(N), y
    Ntot = rng.poisson(Lam * T, N)
    m = Ntot if L is None else np.minimum(Ntot, L)
    probs = [lam[s] / Lam for s in combo]
    n = rng.multinomial(m, probs)
    pesos = np.array([d[s] ** 2 for s in combo])
    delta2 = n @ pesos
    scores = rng.normal((y.astype(float) - 0.5) * delta2, np.sqrt(delta2))
    return scores, y


def janela_ultimos(tempos, L):
    """Return the indices of the ``L`` most recent events, in increasing order of recency.

    Ties in time are broken by input order: the event that appears LATER counts as more recent.
    A history with ``len <= L`` is returned whole.
    """
    tempos = np.asarray(tempos)
    ordem = np.argsort(tempos, kind="stable")
    if L is None or len(tempos) <= L:
        return ordem
    return ordem[-L:]


def simular_literal(combo, lam, d, T, N, rng, L=L_JANELA):
    """Simulate literally: event times and attributes are drawn and the window is truncated.

    Vectorised with ``np.lexsort`` (no Python loop per event); the recency rule is the same as
    in ``janela_ultimos``.
    """
    y = rng.random(N) < PI
    k = len(combo)
    lams = np.array([lam[s] for s in combo])
    d_combo = np.array([d[s] for s in combo])

    contagens = rng.poisson(lams[None, :] * T, size=(N, k))
    total_por_usuario = contagens.sum(axis=1)
    total_eventos = int(total_por_usuario.sum())
    if total_eventos == 0:
        return np.zeros(N), y

    usuarios_grid, fontes_grid = np.meshgrid(np.arange(N), np.arange(k), indexing="ij")
    repeticoes = contagens.ravel()
    usuario_idx = np.repeat(usuarios_grid.ravel(), repeticoes)
    fonte_idx = np.repeat(fontes_grid.ravel(), repeticoes)

    tempos = rng.uniform(0.0, T, size=total_eventos)
    x = rng.normal(d_combo[fonte_idx] * y[usuario_idx].astype(float), 1.0, size=total_eventos)

    # sort by user, then time, then input order (recency tie-break)
    idx_original = np.arange(total_eventos)
    ordem = np.lexsort((idx_original, tempos, usuario_idx))

    fim = np.cumsum(total_por_usuario)
    inicio = fim - total_por_usuario
    inicio_por_posicao = np.repeat(inicio, total_por_usuario)
    tamanho_por_posicao = np.repeat(total_por_usuario, total_por_usuario)
    rank_no_bloco = np.arange(total_eventos) - inicio_por_posicao

    if L is None:
        visivel = np.ones(total_eventos, dtype=bool)
    else:
        limite = np.maximum(tamanho_por_posicao - L, 0)
        visivel = rank_no_bloco >= limite

    indices_visiveis = ordem[visivel]
    contrib = d_combo[fonte_idx] * (x - d_combo[fonte_idx] / 2)
    scores = np.bincount(
        usuario_idx[indices_visiveis], weights=contrib[indices_visiveis], minlength=N
    )
    return scores, y


# --- falsification criterion --------------------------------------------------------------------


def _media_var(valores):
    """Return (mean, sample variance with ddof=1, count) of the values."""
    valores = np.asarray(list(valores), dtype=float)
    media = float(np.mean(valores))
    var = float(np.var(valores, ddof=1)) if len(valores) > 1 else 0.0
    return media, var, len(valores)


def avaliar_quebra(linhas) -> dict:
    """Apply the pre-registered falsification criterion Q1/Q2/Q3 to result rows.

    Analytic predictions are recomputed from the parameters of each row (an ``auc_analitica``
    column, if present, is ignored). Incomplete data raises ``ValueError``, never a silent NaN.

    Parameters
    ----------
    linhas : iterable of dict
        One row per (cell, combination, seed) with the grid parameters and the empirical ``auc``.

    Returns
    -------
    dict
        ``{"Q1": ..., "Q2": ..., "Q3": ...}``, each with its ``falhou`` flag and counts.
    """
    parametros_por_celula: dict[int, dict] = {}
    auc_por_celula_combo: dict[tuple, dict] = defaultdict(dict)

    for row in linhas:
        i_celula = row["i_celula"]
        if i_celula not in parametros_por_celula:
            parametros_por_celula[i_celula] = {
                "T": row["T"],
                "lam": {"A": row["lam_A"], "B": row["lam_B"], "C": row["lam_C"]},
                "d": {"A": row["d_A"], "B": row["d_B"], "C": row["d_C"]},
            }
        auc_por_celula_combo[(i_celula, row["combo"])][row["semente"]] = row["auc"]

    # --- validation: incomplete data is an explicit ValueError, never a silent NaN ---------------
    for i_celula in parametros_por_celula:
        faltando = [c for c in COMBOS if (i_celula, c) not in auc_por_celula_combo]
        if faltando:
            raise ValueError(f"célula {i_celula}: faltam os combos {faltando}")

    # --- Q1: monotonicity in lam_C, saturated cells with d_C == 0 --------------------------------
    violacoes_q1 = []
    pares_testados_q1 = 0
    for combo in ("AC", "BC", "ABC"):
        grupos = defaultdict(list)
        for i_celula, p in parametros_por_celula.items():
            if p["d"]["C"] != 0:
                continue
            chave = (p["T"], p["lam"]["A"], p["lam"]["B"], p["d"]["A"], p["d"]["B"])
            grupos[chave].append((p["lam"]["C"], i_celula))

        for itens in grupos.values():
            itens.sort(key=lambda t: t[0])
            for (lam_c_1, i1), (lam_c_2, i2) in itertools.pairwise(itens):
                if any(lam_c_1 < g < lam_c_2 for g in GRADE_LAM_C):
                    raise ValueError(
                        f"grupo com lam_C em {[t[0] for t in itens]}: falta valor canônico "
                        f"entre {lam_c_1} e {lam_c_2} (par não-consecutivo)"
                    )
                p1, p2 = parametros_por_celula[i1], parametros_por_celula[i2]
                if not (
                    saturada(combo, p1["lam"], p1["T"]) and saturada(combo, p2["lam"], p2["T"])
                ):
                    continue
                pares_testados_q1 += 1
                media1, _, _ = _media_var(auc_por_celula_combo.get((i1, combo), {}).values())
                media2, _, _ = _media_var(auc_por_celula_combo.get((i2, combo), {}).values())
                if not (media2 < media1):
                    violacoes_q1.append(
                        {
                            "combo": combo,
                            "i_celula_1": i1,
                            "i_celula_2": i2,
                            "lam_C_1": lam_c_1,
                            "lam_C_2": lam_c_2,
                            "media_1": media1,
                            "media_2": media2,
                        }
                    )
    q1 = {
        "falhou": len(violacoes_q1) > 0,
        "pares_testados": pares_testados_q1,
        "violacoes": violacoes_q1,
    }

    # --- Q2: sign of adding C (A->AC, B->BC, AB->ABC) --------------------------------------------
    pares_q2 = (("A", "AC"), ("B", "BC"), ("AB", "ABC"))
    comparacoes = abaixo_limiar = empate = testadas = discordantes = 0
    for i_celula, p in parametros_por_celula.items():
        for sem_combo, com_combo in pares_q2:
            comparacoes += 1
            media_sem, var_sem, k_sem = _media_var(
                auc_por_celula_combo.get((i_celula, sem_combo), {}).values()
            )
            media_com, var_com, k_com = _media_var(
                auc_por_celula_combo.get((i_celula, com_combo), {}).values()
            )
            prev = auc_analitica(com_combo, p["lam"], p["d"], p["T"]) - auc_analitica(
                sem_combo, p["lam"], p["d"], p["T"]
            )
            emp = media_com - media_sem
            se = math.sqrt(var_com / k_com + var_sem / k_sem) if k_com and k_sem else 0.0
            if abs(prev) < 0.005:
                abaixo_limiar += 1
            elif abs(prev) < 3 * se:
                empate += 1
            else:
                testadas += 1
                if np.sign(emp) != np.sign(prev):
                    discordantes += 1
    frac_discordante = discordantes / testadas if testadas else 0.0
    q2 = {
        "falhou": frac_discordante > 0.05,
        "comparacoes": comparacoes,
        "testadas": testadas,
        "empate": empate,
        "abaixo_limiar": abaixo_limiar,
        "discordantes": discordantes,
        "frac_discordante": frac_discordante,
    }

    # --- Q3: P3 sign pattern on the empirical mean AUCs ------------------------------------------
    celulas_padrao = celulas_ordem = concordancia = 0
    for i_celula, p in parametros_por_celula.items():
        empirico = {}
        for combo in COMBOS:
            media, _, k = _media_var(auc_por_celula_combo.get((i_celula, combo), {}).values())
            empirico[combo] = media if k else float("nan")
        analitico = {c: auc_analitica(c, p["lam"], p["d"], p["T"]) for c in COMBOS}
        if padrao_p3(empirico):
            celulas_padrao += 1
        if ordem_completa(empirico):
            celulas_ordem += 1
        if padrao_p3(empirico) == padrao_p3(analitico):
            concordancia += 1
    q3 = {
        "falhou": celulas_padrao == 0,
        "celulas_padrao": celulas_padrao,
        "celulas_ordem": celulas_ordem,
        "concordancia_padrao_com_analitico": concordancia,
    }

    return {"Q1": q1, "Q2": q2, "Q3": q3}


def resumo_shortfall(linhas) -> dict:
    """Return the shortfall ratio per cell and the count of cells with the Table 4 pattern.

    The ratio is ``(1 - AUC_X) / (1 - AUC_ABC)`` computed on the MEAN over seeds of each
    (cell, combination): mean first, ratio second. The T4 pattern counts the cells in which the
    three additions of C increase the shortfall and the two additions of B reduce it, i.e.
    ``padrao_p3`` without the extra condition ``C < min(A, B)``.
    """
    auc_por_celula_combo: dict[tuple, dict] = defaultdict(dict)
    for row in linhas:
        auc_por_celula_combo[(row["i_celula"], row["combo"])][row["semente"]] = row["auc"]

    shortfall_por_celula: dict[int, dict] = {}
    shortfall_padrao_T4 = 0
    for i_celula in sorted({i for i, _ in auc_por_celula_combo}):
        media = {c: _media_var(auc_por_celula_combo[(i_celula, c)].values())[0] for c in COMBOS}
        base = 1 - media["ABC"]
        shortfall_por_celula[i_celula] = {c: (1 - media[c]) / base for c in COMBOS if c != "ABC"}
        if (
            media["AC"] < media["A"]
            and media["BC"] < media["B"]
            and media["ABC"] < media["AB"]
            and media["AB"] > media["A"]
            and media["BC"] > media["C"]
        ):
            shortfall_padrao_T4 += 1

    return {
        "shortfall_por_celula": shortfall_por_celula,
        "shortfall_padrao_T4": shortfall_padrao_T4,
    }


# --- grid execution -----------------------------------------------------------------------------


def _rodar_uma_linha(tarefa, N):
    """Simulate one (cell, combination, seed) task by the reduction and return its result row."""
    i_celula, cel, combo, i_combo, semente = tarefa
    rng = rng_para(semente, i_celula, i_combo)
    scores, y = simular_reducao(combo, cel["lam"], cel["d"], cel["T"], N, rng)
    auc = auc_mann_whitney(scores, y)
    n_pos = int(np.sum(y))
    n_neg = N - n_pos
    return {
        "i_celula": i_celula,
        "T": cel["T"],
        "lam_A": cel["lam"]["A"],
        "lam_B": cel["lam"]["B"],
        "lam_C": cel["lam"]["C"],
        "d_A": cel["d"]["A"],
        "d_B": cel["d"]["B"],
        "d_C": cel["d"]["C"],
        "combo": combo,
        "semente": semente,
        "auc": auc,
        "auc_analitica": auc_analitica(combo, cel["lam"], cel["d"], cel["T"]),
        "saturada": saturada(combo, cel["lam"], cel["T"]),
        "n_pos": n_pos,
        "n_neg": n_neg,
    }


def rodar_grade(N=200_000, sementes=range(5), processos=None, celulas_idx=None) -> list[dict]:
    """Run the grid: one row per (cell, combination, seed).

    The output is sorted by ``(i_celula, i_combo, semente)`` and is deterministic regardless of
    the number of processes.
    """
    todas = celulas()
    indices = range(len(todas)) if celulas_idx is None else celulas_idx

    tarefas = [
        (i_celula, todas[i_celula], combo, i_combo, semente)
        for i_celula in indices
        for i_combo, combo in enumerate(COMBOS)
        for semente in sementes
    ]

    if processos is None:
        processos = max(1, (os.cpu_count() or 3) - 2)

    with ProcessPoolExecutor(max_workers=processos) as ex:
        resultados = list(ex.map(_rodar_uma_linha, tarefas, itertools.repeat(N)))

    resultados.sort(key=lambda row: (row["i_celula"], COMBOS.index(row["combo"]), row["semente"]))
    return resultados
